[package]
name = "heat_player"
version = "0.1.0"
authors = ["Jacob Haslehurst <jacob@haslehurst.net>"]

[dependencies]
gtk = "0.4.1"
relm = "0.14.6"
relm-derive = "0.14.6"

[features]
default = ["relm/unstable", "relm-derive/unstable"]
